### ISSUE TITLE
Showing Tooltip Programmatically Make it Disappear Straight Away

### ISSUE THREAD

**Issue by pete-experimenter** [stevenbenner/jquery-powertip#127]
As per #118 I have built powertip from HEAD, but this leads to the following bug:
* Click on either of the buttons Show for Eelement 1/Show for Eelement 2
* Tooltip shows and quickly disappears.

Check http://jsfiddle.net/GuRS6/98/. 

I understand that this is not a release version and yaddy-yada, but as per #118 I was suggested to go on dev version, as the #118 bug is fixed. It is true and the bug is fixed, but the in-dev one has this bug though. So, raising it.

Tested on:
* Win Chrome (39.0.2171.95 m),
* Win Firefox (34.0.5).

**Comment by stevenbenner** [comment]
Fixed in commit e807434713fe0cdd04c2c40af4b4706bcdab0c60.

**Comment by pete-experimenter** [comment]
Thank you for the fix! Will check.
