### ISSUE TITLE
browserify support

### ISSUE THREAD

**Issue by maiermic** [stevenbenner/jquery-powertip#130]
Is it possible to require [jquery-powertip version on npm](https://www.npmjs.com/package/jquery-powertip) using [browserify](http://browserify.org/)? If I call `require('jquery-powertip')` I get an error `Cannot find module 'jquery-powertip'`. Did I do something wrong or is browserify not supported?

**Comment by stevenbenner** [comment]
Unfortunately PowerTip isn't set up at the moment to work with browserify. That is something I'm working on fixing already.

It's also worth noting that the npm package you linked wasn't actually published by me. It looks like it was published by a PowerTip user. I suppose I should see if I can get ownership of that package.

**Comment by stevenbenner** [comment]
Browserify support has been implemented and unit tests added to verify compatibility. I've also updated the documentation to include an "Installation" section that notes how to use PowerTip with Browserify.

This task is completed. It will be part of the next release (version 1.3.0).
