### ISSUE TITLE
Tip closed when mouse cursor goes over iframe scroll bar 

### ISSUE THREAD

**Issue by dyankiya** [stevenbenner/jquery-powertip#133]
Powertip window fades when used with latest IE(11.0.9600.17633) and iframe, and when mouse cursor goes over the scrollbar of the iframe. This does not happen neither with Chrome(40.0.2214.115 m) or Firefox(31.0).  

You can see the code and actual behavior here:
http://goo.gl/qj5mro 

Thanks,
D

**Comment by stevenbenner** [comment]
*I apologize for the delayed reply, work has been keeping me way too busy lately.*

It seem that Internet Explorer is firing a `mouseleave` event on the `iframe` element when you mouse over the scroll bar.

A quick fix for this would be to [`stopPropagation()`](https://api.jquery.com/event.stopPropagation/) on the event.

For example:

```javascript
var privacyTip = $('.powertip'),
	content = $('<p style="width: 400px; white-space:normal; text-align:center">TEST<iframe src="http://www.donatio.biz/english/test2.html" width="400" height="400" frameborder="0" scrolling="yes" style="margin-top:10"></iframe></p>');

content.find('iframe').on('mouseleave', function (e) {
	// prevent this event from bubbling to the tooltip div
	// and causing it to close
	e.stopPropagation();
})

privacyTip.data('powertipjq', content);
privacyTip.powerTip({ placement: 'se', mouseOnToPopup: true });
```

I'm not sure if I should handle this scenario in PowerTip itself. I can check to see if the event target is not the tooltip div, but I will need to verify that there are not situations where we expect the event to have a different target.

**Comment by stevenbenner** [comment]
There hasn't been any interest in this issue in a long time. It seems to me that it is currently too much of a corner case to justify adding special handling in PowerTip.

If anyone finds this issue and wants to argue for it to be included then please leave your comments below.

Closing issue.
