### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by amiremami** [stevenbenner/jquery-powertip#143]
Hi
I want to know can I show thumbnail and excerpt of a internal hyperlink of my website in a hover tooltip same as this? (Fetch them automatically, I don't want insert excerpt and thumbnail manually)

http://www.phonearena.com/news/PSA-To-keep-your-30GB-of-free-OneDrive-cloud-storage-you-must-opt-in-before-Monday_id77862

**Comment by stevenbenner** [comment]
That would require some kind of backend service that would fetch the content, take a screenshot, and try to parse an excerpt.

A screenshot of a remote web page is basically not possible with JavaScript, though there are [screenshot services](https://www.google.com/#q=screenshot+service) that can do this for you.

The excerpt is much more complicated than it sounds. While it should be possible to fetch web page HTML via AJAX (if it's on the same domain or enabled with [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)), parsing the HTML content in JavaScript to find text from the main content area would be very, very tricky. You could write your own excerpt on each page and hide it with CSS, then try to find that element in the DOM.

All in all, this is well outside the scope of a little tooltip plugin. It isn't impossible, but it has a lot of complexity involved.

**Comment by amiremami** [comment]
Thanks :) I have found this one which works fine:
https://wordpress.org/plugins/linkpreview/

**Comment by stevenbenner** [comment]
Nice! I'm glad that there was something ready-made that fits your requirements.
