### ISSUE TITLE
Keep up the good work

### ISSUE THREAD

**Issue by mgibbs189** [stevenbenner/jquery-powertip#152]
Hey @stevenbenner 

I've been using powertip for years and it's been flawless. Just wanted to say thanks, and that I'm very much looking forward to v1.3!

Cheers 🍻

**Comment by stevenbenner** [comment]
Thanks for the kudos! 1.3 is coming down the pipe, just slowly because I've been so busy and doing the full regression tests take a lot of time.

Soon™!
