### ISSUE TITLE
Prevent tooltip opening if input trigger element has focus

### ISSUE THREAD

**Issue by evbrew** [stevenbenner/jquery-powertip#159]
Hello, more of a how-to than an issue.

I'm using PowerTip on an input element to display a Tip containing an icon that executes a function (it copies the value of the input to all other inputs in the same column).

![image](https://user-images.githubusercontent.com/29763631/27663994-075edaba-5c1a-11e7-8f06-de17ba0db6ed.png)

I have AJAX validation that occurs on the inputs onBlur event, so i don't want users to see the Tip while the field has focus (so they have to mouse out, which applies the onBlur validation, then they can use the Tip function).

I'm using the following instantiation options for PowerTip:

elRef.powerTip({
	placement: 'e',
	mouseOnToPopup: true,
	smartPlacement: true,
	openEvents: [ 'mouseenter' ],
	closeEvents: [ 'mouseleave', 'focus' ],
	closeDelay: 750
});

It almost works since I've specified 'focus' as a closeEvent, but if the user gives focus to the input, then mouse outs of the field, if they mouse back over the input the Tip is shown as its triggered by the 'mouseenter' openEvent (since it doesn't correlate the closeEvents to current state - understandable) even though the input still has focus.

Any thoughts, tips or solutions appreciated.

**Comment by stevenbenner** [comment]
This is kind of an unusual case. You don't want tooltips to show unless a specific case is me (element does not have focus).

I think your best bet will be [Custom PowerTip Integration](https://stevenbenner.github.io/jquery-powertip/#custom-powertip-integration). Because that will give you the chance to add logic to prevent to tooltip opening.

**Example:**

```javascript
// run PowerTip - but disable the default event hooks
elRef.powerTip({
	placement: 'e',
	mouseOnToPopup: true,
	smartPlacement: true,
	closeDelay: 750,
	manual: true
});

// hook custom mouse events
elRef.on({
	mouseenter: function(event) {
		// abort if this element has focus
		if ($(this).is(":focus")) {
			return;
		}

		// show tooltip
		$.powerTip.show(this, event);
	},
	mouseleave: function() {
		// hide tooltip
		$.powerTip.hide(this);
	},
	focus: function() {
		// hide tooltip immediately on focus
		$.powerTip.hide();
	}
});
```

(untested - but I think this should do what you want)

**Comment by evbrew** [comment]
No problem, PowerTip is a great tool and this use case was certainly a bit outside of what its intended to do (more of an ad-hoc menu or action context extension in this case).

Thanks for taking a look into my question, much appreciated.

**Comment by stevenbenner** [comment]
Implementing support for this is looking too messy to me. I think we'll just have to accept this as a limitation of PowerTip.

If anyone finds this issue and has a clever solution or just wants to argue in favor of it then please leave your thoughts below.

Closing issue.
