### ISSUE TITLE
Question: Powertip on elements loaded through jQuery .load() function not using CSS

### ISSUE THREAD

**Issue by thisissaf** [stevenbenner/jquery-powertip#162]
Hi there,

I am building a website in which I partly load content (php) inside an existing DIV with the jQuery .load() function. The newly included php includes div's with a 'tooltip' class that should show the PowerTip tooltip. And they do... but the CSS is not applied. The elements that were already on stage without using .load() are showing the tooltip correct. The dynamically loaded elements show the power tip in wrong styling. 

Any ideas on how to solve this would be greatly appreciated!
Thanks

**Comment by stevenbenner** [comment]
It's difficult to picture what kind of problem you're experiencing. What CSS is missing? What do the tooltips look like when they are having the problem? Do you run `.powerTip()` after you inject the content with jQuery's `.load()` method?

Without being able to see the problem there isn't much I can do. Can you provide me with some kind of simplified example (jsfiddle, html/js/css page, url)?

**Comment by stevenbenner** [comment]
There hasn't been any response to this issue for a while, so I'm going to go ahead and close it.

If you have more info that can help to debug this then please reply back with the defails and I'll take a look and reopen this issue if needed.
