### ISSUE TITLE
Question: Way to see if tip is opened

### ISSUE THREAD

**Issue by jm109344** [stevenbenner/jquery-powertip#163]
Hi,
 Just started using this plug-in, I have a situation where I would like to know if the tip is showing or not. I do not see any methods for this, and googling didn't show anything useful (although sometimes my google skills are lacking). If you need an example you can see this rather contrived one [http://jsfiddle.net/jm109344/x7xeqark/4/](url)

**Comment by stevenbenner** [comment]
There isn't anything built into PowerTip itself (though maybe there should be?). However you can check the tooltip element itself. The default id is `#powerTip`, so you should be able to check like this:

```javascript
var isTooltipOpen = $('#powerTip').is(':visible');
```

**Comment by stevenbenner** [comment]
It seems that the question has been answered satisfactorily. Closing issue.

If you have any follow-up questions then please feel free to ask.
