### ISSUE TITLE
Attach powertooltip to range object

### ISSUE THREAD

**Issue by khayati114** [stevenbenner/jquery-powertip#171]
Hi 

1) Is it possible to attach powertooltip to range object instead of HTML element ?

I have been using powertip in my project where we select a range of html elements upon user selection and highlight the same . Upon highlightion we are trying to add some text. Once the text is added we are displaying the same once user hovers on this selection via powertip. Currently we have taken the parentNode of the range object and attached powertip on it. But the issue is that the parentNode can be very far away from actual range selection and thus powertip are displayed quite far away in such cases. So we were wondering to attach the powertip on range object itself so that it appears near/on the selection itself. Is it possible to the same ?

**Comment by stevenbenner** [comment]
Do you mean the range input?

```html
<input type="range" min="-10" max="10" title="Tooltip text">
```

I tried this in Firefox and Chromium and it was working for me. It is worth noting that it will be positioned on the box for the entire input, not just the slider. So if the range input is large then the tooltip may not be very close the the slider.

It may be possible to target the [shadow DOM elements](https://css-tricks.com/sliding-nightmare-understanding-range-input/) of the range input to align to the slider, but those elements are usually protected from scripts and would likely be fragile.

**Comment by khayati114** [comment]
No I am not referring to this. I am referring to [Range Object](http://help.dottoro.com/ljxsqnoi.php)  .This encapsulates a range/series of continuous occurring HTML elements in a HTML document

**Comment by stevenbenner** [comment]
Oh, I see. My mistake.

I believe it would be up to if/how jQuery handles range objects. PowerTip should work on basically anything that can be loaded into jQuery via `$()`, but range objects look like they have some special behavior (like being able to truncate) so they may not be entirely compatible.
