### ISSUE TITLE
Combination of `closeEvents: ['click']` and `mouseOnToPopup: true` doesn't work as expected

### ISSUE THREAD

**Issue by NPException** [stevenbenner/jquery-powertip#173]
Here's a JSFiddle with the behavior: https://jsfiddle.net/7dcgzhu0/

I'm expecting the tooltip to only close on `click`, but it also closes on `mouseleave`.
I need the tooltip to only close on click to overcome an issue where a user with Firefox highlights something in the tooltip and then opens the context menu because he wants to copy the highlighted text. But Firefox triggers  `mouseleave` as soon as the cursor moves onto the context menu.

If I'm not mistaken, the following line should include a check if `mouseLeave` is included in the closeEvents: https://github.com/stevenbenner/jquery-powertip/blob/master/src/tooltipcontroller.js#L145

**Comment by NPException** [comment]
I added a pull request with the changes I made to get it working for me: https://github.com/stevenbenner/jquery-powertip/pull/174

If it is solving the issue the same way you would, you can accept the PR, otherwise feel free to reject it. :)

**Comment by stevenbenner** [comment]
I agree. It doesn't make sense to hook the mouse events for this when the configuration has been changed to explicitly exclude mouse events.

Your pull request was accepted and merged. This fix will go out with the next release.
