### ISSUE TITLE
question regarding adding copy button in the powertip to copy its content

### ISSUE THREAD

**Issue by nalherbawi** [stevenbenner/jquery-powertip#180]
i am trying to add a copy button to be able to copy the content of the power it. the button or icon will be in the power tip itself. but i am facing issues with calling a function from inside the function that show the tip. when i pass the parameter for the called function that copy the content of the tip to clipboard it will fail as it does not recognize the closing of the function call ")"
here is an example of what i am trying to do in jinja template:

```
<script type = "text/javascript" >
$(function()
 { var mouseOnDiv = $('#celltip{{ ns.id_counter }}');
 var tipContent = $(
 '<p id="myInput{{ ns.id_counter }}" value="{{ test.system_out }}"><b> <font color="#8B0000"> system out: </font>{{ test.system_out }}</b></p><div><button onclick="CopyToClipboard('myInput')">copy</button></div>'
);
mouseOnDiv.data('powertipjq', tipContent);
mouseOnDiv.powerTip({
placement: 's',openEvents: ['click'], closeEvents: ['click']
});
});
</script>
function CopyToClipboard(id)
{
var r = document.createRange();
r.selectNode(document.getElementById('id'));
window.getSelection().removeAllRanges();
window.getSelection().addRange(r);
document.execCommand('copy');
window.getSelection().removeAllRanges();
}
</script>
```

**Comment by stevenbenner** [comment]
I may not be understanding the full problem here. But I do see a syntax error in your script:

```javascript
'<p id="myInput{{ ns.id_counter }}" value="{{ test.system_out }}"><b> <font color="#8B0000"> system out: </font>{{ test.system_out }}</b></p><div><button onclick="CopyToClipboard('myInput')">copy</button></div>'
```

The single-quotes in `CopyToClipboard('myInput')` are breaking the string. You probably want to escape those. For example:

```javascript
'<p id="myInput{{ ns.id_counter }}" value="{{ test.system_out }}"><b> <font color="#8B0000"> system out: </font>{{ test.system_out }}</b></p><div><button onclick="CopyToClipboard(\'myInput\')">copy</button></div>'
```

Note the backslashes in `(\'myInput\')`.

I suspect that this will resolve your issue, so I will go ahead and close this bug. Please let me know if the issue persists.
