### ISSUE TITLE
Add a parameter to choose the coloration style of the tooltip

### ISSUE THREAD

**Issue by p4535992** [stevenbenner/jquery-powertip#182]
Add a parameter to choose the color of the tooltip. 
In practice, a parameter like 'placement' that allows the specific tooltip to use the css file 'jquery.powertip-light.css' instead of the default style. 
As a solution for now I use the 'popupClass' parameter and manage by editing the css files with some custom class.

**Comment by stevenbenner** [comment]
I can understand why this could be helpful, but I think it is probably not something that the plugin should handle.

The CSS files that are included with the package are meant as drop-in files needing no configuration, or as templates for developers to adapt to their needs. They all target the same `#powerTip` ID so you cannot use more than one of those files at the same time without modifications.

I think that they way you're handling this is The best way. Basically modify a theme file to target a specific ID, say `#powerTipRed` or update the CSS rules to be a class override. Then when setting up the themed plugins set the `popupId` or `popupClass` options as needed.

For example:
```javascript
$('.tips').powerTip({
    popupId: 'powerTipRed'
});
```

**Comment by p4535992** [comment]
K no problem, ty for the hard work and this project
