### ISSUE TITLE
jQuery Migrate warning: jQuery.type is deprecated

### ISSUE THREAD

**Issue by m-ober** [stevenbenner/jquery-powertip#186]
jQuery 3.6.4 with Migrate 3.4.1 gives the following warning:

> MIGRATE: jQuery.type is deprecated

in:

```javascript
if ($.type(opts) === 'string' && $.powerTip[opts]) {
```

This seems to be the only warning :)

**Comment by stevenbenner** [comment]
This change will be required to support jQuery 4.0.0.

I'll refactor this for the PowerTip 1.3.3 release.

**Comment by stevenbenner** [comment]
Fixed in commit 44bd9c082b27d15778b71beb03629a1e2ac7a656.

This change will be included in the next PowerTip release.

Thank you for the issue report.
