### ISSUE TITLE
The Arrows are not visible in IE8

### ISSUE THREAD

**Issue by chickenwing** [stevenbenner/jquery-powertip#83]
It seems, that IE8 has some problem with rendering pseudoelements(the arrows) of elements that are inserted by javascript...

A possible solution is documented here: http://stackoverflow.com/a/8852418/228450

**Comment by stevenbenner** [comment]
This should be resolved, or at least hopefully improved by commit 2ca0cd1d6282f0e2103adeae4a16864692d7638e.
